### ISSUE TITLE
Верстка

### ISSUE THREAD

**Issue by vak1n** [Kirill1001/first_project#1]
По верстке все отлично, но есть несколько вопросов и пожеланий.
1. Меню в мобильной версии не раскрывается http://joxi.ru/82QWzk0ijWJV1r
2. При нажатии на пункты меню ссылки подчеркиваются и изменяют цвет
http://joxi.ru/brRdb1JSJEqLG2
http://joxi.ru/Dr8oLXZF45qJRA
3. При клике на меню личного кабинета ссылка также подчеркивается http://joxi.ru/a2X7Pqbc1WjQOm
4. Изображения и названия в превью как правило являются ссылками на детальную страницу 
http://joxi.ru/gmvjG0nhLRjBJm
http://joxi.ru/5mdGZO4ukLl1zr
http://joxi.ru/L213YKQf8xkVXr
5. Оправдано ли тянуть весь бутстрап если мы используем только его малую часть? http://getbootstrap.com/customize/

**Comment by Kirill1001** [comment]
поправил все пункты, кроме первого(нужен js), могу применять jquery для меню?

**Comment by vak1n** [comment]
> поправил все пункты,

ok, отправляй, посмотрим.

> кроме первого(нужен js), могу применять jquery для меню?

Раз нужен js, выделим в отдельную задачу #6. jQuery применять можно.

**Comment by Kirill1001** [comment]
отправил изменения на удаленный репозиторий.
___
могу я подключать js библиотеки и плагины с помощью CDN?

**Comment by vak1n** [comment]
Да, конечно.

**Comment by vak1n** [comment]
В пункте четыре пропустил названия у новостей:

> Изображения и названия в превью как правило являются ссылками на детальную страницу
> http://joxi.ru/L213YKQf8xkVXr

Или намерено так оставил?

**Comment by Kirill1001** [comment]
пропустил, сейчас поправлю

**Comment by Kirill1001** [comment]
поправил ссылки в секции с новостями

**Comment by vak1n** [comment]
Ok. Переноси в мастер.
