### ISSUE TITLE
Карусель (слайдер) товаров

### ISSUE THREAD

**Issue by vak1n** [Kirill1001/first_project#2]
Добавим карусель с товарами http://joxi.ru/5mdGZO4uvljzVr.

Нужно подобрать подходящее решение или jQuery плагин и интегрировать его в верстку.

**Comment by Kirill1001** [comment]
Для карусели решил использовать [Owl Carousel](https://owlcarousel2.github.io/OwlCarousel2/). У него хорошая поддержка, думаю это оптимальный выбор.

**Comment by Kirill1001** [comment]
Карусель готова, отправил на репозиторий.

**Comment by Kirill1001** [comment]
слайдер могу переносить?

**Comment by vak1n** [comment]
Все норм. Но как в ветку попали правки из задачи #1 если их еще нет в мастере? ) При добавлении новой фичи ветвится необходимо от мастера, так как эта ветка считается стабильной.
