### ISSUE TITLE
Вкладки (табы) коллекций с товарами

### ISSUE THREAD

**Issue by vak1n** [Kirill1001/first_project#3]
Добавим переключение вкладок с товарами http://joxi.ru/Rmzvl01fWxqPWm.

Нужно подобрать подходящее решение или jQuery плагин и интегрировать его в верстку.

**Comment by Kirill1001** [comment]
Табы должны фильтровать товар, я правильно понял?

**Comment by vak1n** [comment]
Можно и так сказать, т.е. показывать товары определенного раздела или все. Дополнительные товары (названия, изображения, описание) добавлять на свое усмотрение, но желательно чтобы эти товары подходили по смыслу раздела (таба).

**Comment by Kirill1001** [comment]
сделал фильтрацию товаров и отправил на репозиторий

**Comment by vak1n** [comment]
Тестирование  в FireFox:

1. При клике на название таба кидает в вверх страницы (в хроме нет)
2. При переключении вкладки название активного таба не изменяется

![peek 2017-07-14 15-49](https://user-images.githubusercontent.com/11799289/28212871-2ba26ac4-68ac-11e7-8e32-e411b991d2e2.gif)

**Comment by vak1n** [comment]
_**Коммиты не появляются в ленте, забываешь связывать их с задачами. Как это делать высылал на почту.**_

**Comment by Kirill1001** [comment]
поправил баг в Firefox, залил на репозиторий

**Comment by Kirill1001** [comment]
Изменил фильтрацию, учел возможность увеличения количества вкладок

**Comment by Kirill1001** [comment]
добавил переключение активной ссылки по категориям товаров

**Comment by Kirill1001** [comment]
добавил комментарии для фильтра

**Comment by vak1n** [comment]
Ok, на данном этапе этого достаточно. Добавляй в мастер.

**Comment by Kirill1001** [comment]
слил ветку с мастером
