### ISSUE TITLE
Корзина товаров

### ISSUE THREAD

**Issue by vak1n** [Kirill1001/first_project#5]
Добавим корзину товаров и возможность добавление товара в эту корзину http://joxi.ru/E2pM8jKCBod9JA. 

В шапке должно выводится количество находящихся в корзине товаров. Через час с момента последнего добавления товара корзина должна очищаться.

Хранение данных реализовать через локальное хранилище браузера localStorage.

**Comment by Kirill1001** [comment]
Сделал корзину, отправил в репозиторий.

**Comment by vak1n** [comment]
Отлично, добавляй в мастер.
