### ISSUE TITLE
Меню в мобильной версии

### ISSUE THREAD

**Issue by vak1n** [Kirill1001/first_project#6]
Добавим меню в мобильной версии http://joxi.ru/82QWzk0ijWJV1r динамику. При клике на иконку должно выводится скрытое верхнее меню. А раз дизайн для мобильных устройств отсутствует, вид меню на свое усмотрение.

**Comment by Kirill1001** [comment]
Добавил выпадающее меню для мобильной версии

**Comment by vak1n** [comment]
Отлично. Переноси в мастер.

**Comment by Kirill1001** [comment]
при сливании ветки возник конфликт, исправил его, после этого слил ветку в мастер
